### ISSUE TITLE
add new fields to user model

### ISSUE THREAD

**Issue by vitorandrietta** [mupi/tecsaladeaula#45]
**-- Escola/Instituição em que atua
-- Tipo da Escola
-- Cidade/Estado
-- Cargo
-- Nível de ensino em que atua
-- Ano/Série
-- Disciplina/Área do conhecimento**

**Comment by rlage** [comment]
@vitorandrietta , this issue is just to change the model, right? We should have at least one more issue to change the fields in the front-end (since the database is updated by django migrate command)

**Comment by vitorandrietta** [comment]
@rlage , you are right.

**Comment by vitorandrietta** [comment]
wich new fields we need to cover in accounts Serializer ?
[Accounts Serializers](https://github.com/mupi/tecsaladeaula/blob/develop/accounts/serializers.py)
